### ISSUE TITLE
Blockfolio link

### ISSUE THREAD

**Issue by ohcee** [Veil-Project/veil-project.github.io#51]
The *blockfolio* link is one of the main links on our main page and throughout the website it can be found. When clicked on you get taken here. 
![Screenshot 2023-05-07 at 3 47 57 PM](https://user-images.githubusercontent.com/46406370/236706296-39f13c6d-3440-4ffe-bf42-662db714671c.png)
Should probably take it down.

**Comment by seanPhill** [comment]
Yeah! Too bad they got taken over by that FTX scam!

**Comment by seanPhill** [comment]
Fixed with PR #54
