### ISSUE TITLE
nosofast picture

### ISSUE THREAD

**Issue by ohcee** [Veil-Project/veil-project.github.io#52]
The nosofast avatar on the main page has an error with the picture. 
![Screenshot 2023-05-07 at 3 52 52 PM](https://user-images.githubusercontent.com/46406370/236706443-4df613b4-8007-4370-8f3f-ca0e67c32f70.png)

**Comment by seanPhill** [comment]
![Screen Shot 2023-05-08 at 1 28 13 pm](https://user-images.githubusercontent.com/46495592/236727419-8b6fa473-4cc6-4016-bdd2-97e91fdfdd52.png)

Finding a suitable replacement.

**Comment by seanPhill** [comment]
Fixed with PR #55
