### ISSUE TITLE
RIngCT and Stealth papers

### ISSUE THREAD

**Issue by ohcee** [Veil-Project/veil-project.github.io#53]
In the FAQ section under *Where can I learn more about the privacy technologies implemented in Veil? *. The RingCT paper and the stealth paper links don't work. 
![Screenshot 2023-05-07 at 3 55 12 PM](https://user-images.githubusercontent.com/46406370/236706659-1804b00a-2257-4bd1-a256-181621f2f62e.png)

**Comment by seanPhill** [comment]
Monero has changed server sub-domains. ... Adjusting.
AND cryptonote.org is no longer found. ...

**Comment by seanPhill** [comment]
Fixed with PR #56 
Thanks!
