### ISSUE TITLE
notsofast picture

### ISSUE THREAD

**Issue by ohcee** [Veil-Project/veil-project.github.io#59]
Image is still broken on the main page. The other twitter avatars are visible just not this one.
![Screenshot 2023-05-10 at 5 34 47 AM](https://github.com/Veil-Project/veil-project.github.io/assets/46406370/cd5724e2-b253-488f-aa93-18a93dc7e2a3)

**Comment by seanPhill** [comment]
I think this happened because he changed his Twitter profile pic again and deleted the old one. I would rather this picture remain whatever it was four years ago. Gone to waybackmachine.
