### ISSUE TITLE
" -->" showing at the top of the website!

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil-project.github.io#82]
This commit <https://github.com/Veil-Project/veil-project.github.io/commit/2f34a5fe8ed68aba1b22c8113d45d9131313b4a1#commitcomment-138696269> was made to try to fix this artefact, which only happens on the public website. No sign of the problem when hosted locally using Jekyll.

Anyone got an explanation for this?

On mobile if you scroll down and then scroll up you don't see the ` -->` again, but in a desktop browser if you scroll down and then all the way up it is still there.

**Comment by seanPhill** [comment]
Maybe it's a commented out section in a file type that should not be using that format of commenting out, but bear in mind that there is no problem except on the Github Pages hosted website.

**Comment by seanPhill** [comment]
File types using `<!-- ... -->` include the following, but note that these are not new comments.

- svg (this is an XML type file)
- html
- md

<https://www.jamestharpe.com/markdown-comments/> mentions that Markdown implementations vary with their handling of HTML comments! This could account for the difference.

**Comment by seanPhill** [comment]
Still not fixed! Any ideas, anyone?

**Comment by ohcee** [comment]
There --> is still on the mobile too.  Even when i scrolled down and back up. At least on iPhone.

**Comment by seanPhill** [comment]
Fixed with PR#85 THANKS Ivan!

The start of a _comment out_ HTML line got rendered, while still failing to prevent loading (the unused) Google Analytics, as the Jekyll website builder still reads non-rendered text in the HTML for its instructions.
