### ISSUE TITLE
Add link to WTM on https://veil-project.com/mining/

### ISSUE THREAD

**Issue by codeofalltrades** [Veil-Project/veil-project.github.io#9]
Profitability Calculator 
https://whattomine.com/coins/286-veil-progpow

**Comment by seanPhill** [comment]
I don't have edit rights on this repo, but I have addressed this issue in
https://github.com/Veil-Project/veil-project.github.io/pull/16

**Comment by seanPhill** [comment]
Checking now. I think it was fully committed before now, but it's definitely there now.
